name: PlayerSwap
auther: Cezar
main: me.cezar.Plugin.SwapPlugin
version: 1.0
api-version: 1.16
description: swaps players every 5 minutes

commands:
  start_swap:
    description: starts the tasks of swapping all players every 5 minutes
    usage: /<command>

  stop_swap:
    description: stops the tasks of swapping all players every 5 minutes
    usage: /<command>

  manual_swap:
    description: manually swaps players regardless of gamestate. Mainly for debugging
    usage: /<command>
